TypeRacerWebPageAndAPI/TypeRacerWebPageAndAPI/Models/AccountModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace TypeRacerWebPageAndAPI.Models
{
    public class AccountModel
    {
        public int ID { get; set; }

        [Required]
        public string Username { get; set; }

        [Required]
        public string Password { get; set; }
        public AccountModel() { }
        public AccountModel(string username, string password)
        {
            this.Username = username;
            this.Password = password;
        }
    }
}

TypeRacerWebPageAndAPI/TypeRacerWebPageAndAPI/Models/DatabaseContext.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace TypeRacerWebPageAndAPI.Models
{
    public class DatabaseContext : DbContext
    {
        public DatabaseContext() : base()
        {

        }

        public DbSet<AccountModel> allAccounts { get; set; }
        public DbSet<UserStatisticsModel> allUsersStatistics { get; set; }
        public DbSet<HighscoreModel> allHighscores { get; set; }

    }
}

TypeRacerWebPageAndAPI/TypeRacerWebPageAndAPI/Models/HighscoreModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace TypeRacerWebPageAndAPI.Models
{
    public class HighscoreModel
    {
        public int ID { get; set; }
        public string Player { get; set; }
        public int WordsPerMinute { get; set; }
        public int TimeInSeconds { get; set; }
        public string Map { get; set; }
    }
}

TypeRacerWebPageAndAPI/TypeRacerWebPageAndAPI/Models/UserStatisticsModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TypeRacerWebPageAndAPI.Models
{
    public class UserStatisticsModel
    {
        public int ID { get; set; }
        public string Username { get; set; }
        public int PlayedGames { get; set; }

        public UserStatisticsModel(string Username)
        {
            this.Username = Username;
            this.PlayedGames = 0;
        }

        public UserStatisticsModel() { }
    }
}

TypeRacerWebPageAndAPI/TypeRacerWebPageAndAPI/Controllers/AccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using TypeRacerWebPageAndAPI.Models;

namespace TypeRacerWebPageAndAPI.Controllers
{
    [RoutePrefix("api/account")]
    public class AccountController : ApiController
    {
        public static bool LoginAccount_Helper(AccountModel account)
        {
            foreach (AccountModel acc in HomeController.db.allAccounts)
            {
                if (acc.Username == account.Username && acc.Username == account.Username)
                    return true;
            }

                return false;
        }

        [Route("login")]
        [HttpPost]
        public bool LoginAccount([FromBody] AccountModel account)
        {
            return LoginAccount_Helper(account);
        }

        public static void RegisterAccount_Helper(AccountModel account)
        {
            HomeController.db.allAccounts.Add(new AccountModel(account.Username, account.Password));
            HomeController.db.allUsersStatistics.Add(new UserStatisticsModel(account.Username));

            HomeController.db.SaveChanges();
        }

        [Route("register")]
        [HttpPost]
        public void RegisterAccount([FromBody] AccountModel account)
        {
            RegisterAccount_Helper(account);
        }

    }
}

TypeRacerWebPageAndAPI/TypeRacerWebPageAndAPI/Controllers/HighscoresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using TypeRacerWebPageAndAPI.Models;

namespace TypeRacerWebPageAndAPI.Controllers
{
    [RoutePrefix("api/highscores")]
    public class HighscoresController : ApiController
    {
        [HttpGet]
        public List<HighscoreModel> GetAllHighscores()
        {
            return HomeController.db.allHighscores.OrderBy(o => o.WordsPerMinute).ToList();
        }

        [HttpPost]
        public void AddHighscore([FromBody] HighscoreModel score)
        {
            HighscoreModel temp = new HighscoreModel();

            temp.Player = score.Player;
            temp.WordsPerMinute = score.WordsPerMinute;
            temp.TimeInSeconds = score.TimeInSeconds;
            temp.Map = score.Map;

            HomeController.db.allHighscores.Add(temp);
            HomeController.db.SaveChanges();
        }

    }
}

TypeRacerWebPageAndAPI/TypeRacerWebPageAndAPI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TypeRacerWebPageAndAPI.Models;

namespace TypeRacerWebPageAndAPI.Controllers
{
    public class HomeController : Controller
    {
        public static DatabaseContext db = new DatabaseContext();

        public static string Username { get; set; }
        public static string Password { get; set; }

        public ActionResult Index()
        {
            ViewBag.Message = "My own login page";
            return View();
        }

        public ActionResult Login(AccountModel model)
        {
            bool loginSuccessful = AccountController.LoginAccount_Helper(model);

            if (loginSuccessful)
            {
                Username = model.Username;
                Password = model.Password;

                ViewBag.Message = model.Username;
                ViewBag.PlayedCount = HomeController.db.allUsersStatistics.Single(a => a.Username == model.Username).PlayedGames;
                ViewBag.allScores = HomeController.db.allHighscores.ToList();

                return View("LoginSuccessful", model);
            }
            else
                return View("LoginFailed");
        }
    }
}

TypeRacerWebPageAndAPI/TypeRacerWebPageAndAPI/Controllers/RegisterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TypeRacerWebPageAndAPI.Models;

namespace TypeRacerWebPageAndAPI.Controllers
{
    public class RegisterController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.Message = "Create new account!";
            return View();
        }

        public ActionResult CreateNewAccount(AccountModel account)
        {
            AccountController.RegisterAccount_Helper(account);

            return View("RegistrationSuccessful");
        }
    }
}

TypeRacerWebPageAndAPI/TypeRacerWebPageAndAPI/Controllers/UserStatisticsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using TypeRacerWebPageAndAPI.Models;

namespace TypeRacerWebPageAndAPI.Controllers
{
    [RoutePrefix("api/userstatistics")]
    public class UserStatisticsController : ApiController
    {
        [HttpPost]
        [Route("playedcount")]
        public int PlayedCount([FromBody] AccountModel account)
        {
            UserStatisticsModel acc = HomeController.db.allUsersStatistics.Single(o => o.Username == account.Username);
            if (acc != null)
                return acc.PlayedGames;
            else
                return 0;
        }

        [HttpPost]
        [Route("incrementplayedcount")]
        public void IncrementPlayedCount([FromBody] AccountModel account)
        {
            foreach (UserStatisticsModel actualUser in HomeController.db.allUsersStatistics)
                if (account.Username == actualUser.Username)
                    actualUser.PlayedGames++;
        }
    }
}

TypeRacerWebPageAndAPI/TypeRacerWebPageAndAPI/Views/Home/Index.cshtml
@model TypeRacerWebPageAndAPI.Models.AccountModel

@{
    ViewBag.Title = "Home Page";
}

<h2>@ViewBag.Message</h2>

<hr />

@using (Html.BeginForm("Login", "Home", FormMethod.Post))
{
    <label>Username: </label>
    @Html.TextBoxFor(model => model.Username)
    @Html.ValidationMessageFor(model => model.Username)<br />


    <label>Password: </label>
    @Html.TextBoxFor(model => model.Password)
    @Html.ValidationMessageFor(model => model.Password)<br />

    <button type="submit">Login</button><br /><br />
    <a href="/Register">Don't have account? Click here to register</a>
}

TypeRacerWebPageAndAPI/TypeRacerWebPageAndAPI/Views/Home/LoginFailed.cshtml
<h1>Login failed</h1><br />
<a href="/">Try again</a>

TypeRacerWebPageAndAPI/TypeRacerWebPageAndAPI/Views/Home/LoginSuccessful.cshtml
@{
    ViewBag.Title = "Home Page";
}

<style>
    th, td {
        padding: 15px;
        text-align: left;
        border: 1px solid black;
</style>

@functions
{
    string HelloMessage(string user)
    {
        var msg = "Hi " + user + ", welcome again!";
        return msg;
    }
}

@HelloMessage(@ViewBag.Message)<br />

<label>Played count: @ViewBag.PlayedCount</label><br />

@if (ViewBag.allScores.Count > 0)
{
    @Html.Raw("<table style=\"border: 1px solid black;\">");
    @Html.Raw("<tr>" +
    "<th>No.</th>" +
    "<th>Player</th>" +
    "<th>Words/min</th>" +
    "<th>Time[s]</th>" +
    "<th>Map</th>" +
    "</tr>");
    for (int i = 0; i < @ViewBag.allScores.Count; i++)
    {
        @Html.Raw("<tr>" +
       "<td>" + (i + 1) + "</td>" +
       "<td>" + ViewBag.allScores[i].Player + "</td>" +
       "<td>" + ViewBag.allScores[i].WordsPerMinute + "</td>" +
       "<td>" + ViewBag.allScores[i].TimeInSeconds + "</td>" +
       "<td>" + ViewBag.allScores[i].Map + "</td>" +
       "</tr>");
    }
    @Html.Raw("</table>");
}

TypeRacerWebPageAndAPI/TypeRacerWebPageAndAPI/Views/Register/Index.cshtml
@model TypeRacerWebPageAndAPI.Models.AccountModel

@{
    ViewBag.Title = "Register Page";
}



<h2>@ViewBag.Message</h2>

<hr />

@using (Html.BeginForm("CreateNewAccount", "Register", FormMethod.Post))
{
    <label>Username: </label>
    @Html.TextBoxFor(model => model.Username)
    @Html.ValidationMessageFor(model => model.Username)<br />

    <label>Password: </label>
    @Html.TextBoxFor(model => model.Password)
    @Html.ValidationMessageFor(model => model.Password)<br />

    <button type="submit">Register</button><br /><br />
}

TypeRacerWebPageAndAPI/TypeRacerWebPageAndAPI/Views/Register/RegistrationSuccessful.cshtml
@{
    ViewBag.Title = "Registration completed";
}

<br />
Account created!<br /><br />
<a href="/">You can login now, click here!</a>

TypeRacerWebPageAndAPI/TypeRacerWebPageAndAPI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("TypeRacer", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Register", "Index", "Register", new { area = "" }, new { @class = "navbar-brand" })
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mieszko Dziadowiec s18949, projekt zaliczeniowy na MPR</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>